/* tslint:disable */
/* eslint-disable */
/**
 * Demo Shop API
 * A comprehensive API for managing an online store, providing endpoints for product catalog, user management, shopping cart operations, and order processing
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AddCartItemRequest
 */
export interface AddCartItemRequest {
  /**
   *
   * @type {number}
   * @memberof AddCartItemRequest
   */
  productId: number;
}

/**
 * Check if a given object implements the AddCartItemRequest interface.
 */
export function instanceOfAddCartItemRequest(value: object): value is AddCartItemRequest {
  if (!('productId' in value) || value['productId'] === undefined) return false;
  return true;
}

export function AddCartItemRequestFromJSON(json: any): AddCartItemRequest {
  return AddCartItemRequestFromJSONTyped(json, false);
}

export function AddCartItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddCartItemRequest {
  if (json == null) {
    return json;
  }
  return {
    productId: json['productId'],
  };
}

export function AddCartItemRequestToJSON(json: any): AddCartItemRequest {
  return AddCartItemRequestToJSONTyped(json, false);
}

export function AddCartItemRequestToJSONTyped(
  value?: AddCartItemRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    productId: value['productId'],
  };
}
