/* tslint:disable */
/* eslint-disable */
/**
 * Demo Shop API
 * A comprehensive API for managing an online store, providing endpoints for product catalog, user management, shopping cart operations, and order processing
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AddressResponse
 */
export interface AddressResponse {
  /**
   *
   * @type {string}
   * @memberof AddressResponse
   */
  street: string;
  /**
   *
   * @type {string}
   * @memberof AddressResponse
   */
  apartment: string;
  /**
   *
   * @type {string}
   * @memberof AddressResponse
   */
  city: string;
  /**
   *
   * @type {string}
   * @memberof AddressResponse
   */
  region?: string | null;
  /**
   *
   * @type {string}
   * @memberof AddressResponse
   */
  zip: string;
  /**
   *
   * @type {string}
   * @memberof AddressResponse
   */
  country: string;
}

/**
 * Check if a given object implements the AddressResponse interface.
 */
export function instanceOfAddressResponse(value: object): value is AddressResponse {
  if (!('street' in value) || value['street'] === undefined) return false;
  if (!('apartment' in value) || value['apartment'] === undefined) return false;
  if (!('city' in value) || value['city'] === undefined) return false;
  if (!('zip' in value) || value['zip'] === undefined) return false;
  if (!('country' in value) || value['country'] === undefined) return false;
  return true;
}

export function AddressResponseFromJSON(json: any): AddressResponse {
  return AddressResponseFromJSONTyped(json, false);
}

export function AddressResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressResponse {
  if (json == null) {
    return json;
  }
  return {
    street: json['street'],
    apartment: json['apartment'],
    city: json['city'],
    region: json['region'] == null ? undefined : json['region'],
    zip: json['zip'],
    country: json['country'],
  };
}

export function AddressResponseToJSON(json: any): AddressResponse {
  return AddressResponseToJSONTyped(json, false);
}

export function AddressResponseToJSONTyped(value?: AddressResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    street: value['street'],
    apartment: value['apartment'],
    city: value['city'],
    region: value['region'],
    zip: value['zip'],
    country: value['country'],
  };
}
