/* tslint:disable */
/* eslint-disable */
/**
 * Demo Shop API
 * A comprehensive API for managing an online store, providing endpoints for product catalog, user management, shopping cart operations, and order processing
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ImageResponse
 */
export interface ImageResponse {
  /**
   *
   * @type {string}
   * @memberof ImageResponse
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ImageResponse
   */
  uri: string;
}

/**
 * Check if a given object implements the ImageResponse interface.
 */
export function instanceOfImageResponse(value: object): value is ImageResponse {
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('uri' in value) || value['uri'] === undefined) return false;
  return true;
}

export function ImageResponseFromJSON(json: any): ImageResponse {
  return ImageResponseFromJSONTyped(json, false);
}

export function ImageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageResponse {
  if (json == null) {
    return json;
  }
  return {

    'name': json['name'],
    'uri': json['uri'],
  };
}

export function ImageResponseToJSON(json: any): ImageResponse {
  return ImageResponseToJSONTyped(json, false);
}

export function ImageResponseToJSONTyped(value?: ImageResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'name': value['name'],
    'uri': value['uri'],
  };
}

