/* tslint:disable */
/* eslint-disable */
/**
 * Demo Shop API
 * A comprehensive API for managing an online store, providing endpoints for product catalog, user management, shopping cart operations, and order processing
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface OrderItemResponse
 */
export interface OrderItemResponse {
  /**
   *
   * @type {number}
   * @memberof OrderItemResponse
   */
  productId: number;
  /**
   *
   * @type {string}
   * @memberof OrderItemResponse
   */
  productName: string;
  /**
   *
   * @type {string}
   * @memberof OrderItemResponse
   */
  productThumbnail: string;
  /**
   *
   * @type {number}
   * @memberof OrderItemResponse
   */
  quantity: number;
  /**
   *
   * @type {number}
   * @memberof OrderItemResponse
   */
  unitPrice: number;
  /**
   *
   * @type {number}
   * @memberof OrderItemResponse
   */
  totalPrice: number;
}

/**
 * Check if a given object implements the OrderItemResponse interface.
 */
export function instanceOfOrderItemResponse(value: object): value is OrderItemResponse {
  if (!('productId' in value) || value['productId'] === undefined) return false;
  if (!('productName' in value) || value['productName'] === undefined) return false;
  if (!('productThumbnail' in value) || value['productThumbnail'] === undefined) return false;
  if (!('quantity' in value) || value['quantity'] === undefined) return false;
  if (!('unitPrice' in value) || value['unitPrice'] === undefined) return false;
  if (!('totalPrice' in value) || value['totalPrice'] === undefined) return false;
  return true;
}

export function OrderItemResponseFromJSON(json: any): OrderItemResponse {
  return OrderItemResponseFromJSONTyped(json, false);
}

export function OrderItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderItemResponse {
  if (json == null) {
    return json;
  }
  return {
    productId: json['productId'],
    productName: json['productName'],
    productThumbnail: json['productThumbnail'],
    quantity: json['quantity'],
    unitPrice: json['unitPrice'],
    totalPrice: json['totalPrice'],
  };
}

export function OrderItemResponseToJSON(json: any): OrderItemResponse {
  return OrderItemResponseToJSONTyped(json, false);
}

export function OrderItemResponseToJSONTyped(
  value?: OrderItemResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    productId: value['productId'],
    productName: value['productName'],
    productThumbnail: value['productThumbnail'],
    quantity: value['quantity'],
    unitPrice: value['unitPrice'],
    totalPrice: value['totalPrice'],
  };
}
