/* tslint:disable */
/* eslint-disable */
/**
 * Demo Shop API
 * A comprehensive API for managing an online store, providing endpoints for product catalog, user management, shopping cart operations, and order processing
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderResponse } from './order-response';
import {
  OrderResponseFromJSON,
  OrderResponseFromJSONTyped,
  OrderResponseToJSON,
  OrderResponseToJSONTyped,
} from './order-response';

/**
 *
 * @export
 * @interface OrderListResponse
 */
export interface OrderListResponse {
  /**
   *
   * @type {Array<OrderResponse>}
   * @memberof OrderListResponse
   */
  items: Array<OrderResponse>;
}

/**
 * Check if a given object implements the OrderListResponse interface.
 */
export function instanceOfOrderListResponse(value: object): value is OrderListResponse {
  if (!('items' in value) || value['items'] === undefined) return false;
  return true;
}

export function OrderListResponseFromJSON(json: any): OrderListResponse {
  return OrderListResponseFromJSONTyped(json, false);
}

export function OrderListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderListResponse {
  if (json == null) {
    return json;
  }
  return {
    items: (json['items'] as Array<any>).map(OrderResponseFromJSON),
  };
}

export function OrderListResponseToJSON(json: any): OrderListResponse {
  return OrderListResponseToJSONTyped(json, false);
}

export function OrderListResponseToJSONTyped(
  value?: OrderListResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    items: (value['items'] as Array<any>).map(OrderResponseToJSON),
  };
}
