/* tslint:disable */
/* eslint-disable */
/**
 * Demo Shop API
 * A comprehensive API for managing an online store, providing endpoints for product catalog, user management, shopping cart operations, and order processing
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductResponse } from './product-response';
import {
  ProductResponseFromJSON,
  ProductResponseFromJSONTyped,
  ProductResponseToJSON,
  ProductResponseToJSONTyped,
} from './product-response';

/**
 *
 * @export
 * @interface ProductListResponse
 */
export interface ProductListResponse {
  /**
   *
   * @type {Array<ProductResponse>}
   * @memberof ProductListResponse
   */
  items: Array<ProductResponse>;
}

/**
 * Check if a given object implements the ProductListResponse interface.
 */
export function instanceOfProductListResponse(value: object): value is ProductListResponse {
  if (!('items' in value) || value['items'] === undefined) return false;
  return true;
}

export function ProductListResponseFromJSON(json: any): ProductListResponse {
  return ProductListResponseFromJSONTyped(json, false);
}

export function ProductListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductListResponse {
  if (json == null) {
    return json;
  }
  return {
    items: (json['items'] as Array<any>).map(ProductResponseFromJSON),
  };
}

export function ProductListResponseToJSON(json: any): ProductListResponse {
  return ProductListResponseToJSONTyped(json, false);
}

export function ProductListResponseToJSONTyped(
  value?: ProductListResponse | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    items: (value['items'] as Array<any>).map(ProductResponseToJSON),
  };
}
