/* tslint:disable */
/* eslint-disable */
/**
 * Demo Shop API
 * A comprehensive API for managing an online store, providing endpoints for product catalog, user management, shopping cart operations, and order processing
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageResponse } from './image-response';
import {
  ImageResponseFromJSON,
  ImageResponseFromJSONTyped,
  ImageResponseToJSON,
  ImageResponseToJSONTyped,
} from './image-response';

/**
 *
 * @export
 * @interface ProductResponse
 */
export interface ProductResponse {
  /**
   *
   * @type {number}
   * @memberof ProductResponse
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof ProductResponse
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof ProductResponse
   */
  description: string;
  /**
   *
   * @type {Array<string>}
   * @memberof ProductResponse
   */
  categories: Array<string>;
  /**
   *
   * @type {Array<ImageResponse>}
   * @memberof ProductResponse
   */
  images: Array<ImageResponse>;
  /**
   *
   * @type {number}
   * @memberof ProductResponse
   */
  price: number;
  /**
   *
   * @type {ImageResponse}
   * @memberof ProductResponse
   */
  thumbnail: ImageResponse;
}

/**
 * Check if a given object implements the ProductResponse interface.
 */
export function instanceOfProductResponse(value: object): value is ProductResponse {
  if (!('id' in value) || value['id'] === undefined) return false;
  if (!('name' in value) || value['name'] === undefined) return false;
  if (!('description' in value) || value['description'] === undefined) return false;
  if (!('categories' in value) || value['categories'] === undefined) return false;
  if (!('images' in value) || value['images'] === undefined) return false;
  if (!('price' in value) || value['price'] === undefined) return false;
  if (!('thumbnail' in value) || value['thumbnail'] === undefined) return false;
  return true;
}

export function ProductResponseFromJSON(json: any): ProductResponse {
  return ProductResponseFromJSONTyped(json, false);
}

export function ProductResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductResponse {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    name: json['name'],
    description: json['description'],
    categories: json['categories'],
    images: (json['images'] as Array<any>).map(ImageResponseFromJSON),
    price: json['price'],
    thumbnail: ImageResponseFromJSON(json['thumbnail']),
  };
}

export function ProductResponseToJSON(json: any): ProductResponse {
  return ProductResponseToJSONTyped(json, false);
}

export function ProductResponseToJSONTyped(value?: ProductResponse | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    id: value['id'],
    name: value['name'],
    description: value['description'],
    categories: value['categories'],
    images: (value['images'] as Array<any>).map(ImageResponseToJSON),
    price: value['price'],
    thumbnail: ImageResponseToJSON(value['thumbnail']),
  };
}
