/* tslint:disable */
/* eslint-disable */
/**
 * Demo Shop API
 * A comprehensive API for managing an online store, providing endpoints for product catalog, user management, shopping cart operations, and order processing
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateCartItemQuantityRequest
 */
export interface UpdateCartItemQuantityRequest {
  /**
   *
   * @type {number}
   * @memberof UpdateCartItemQuantityRequest
   */
  quantity: number;
}

/**
 * Check if a given object implements the UpdateCartItemQuantityRequest interface.
 */
export function instanceOfUpdateCartItemQuantityRequest(value: object): value is UpdateCartItemQuantityRequest {
  if (!('quantity' in value) || value['quantity'] === undefined) return false;
  return true;
}

export function UpdateCartItemQuantityRequestFromJSON(json: any): UpdateCartItemQuantityRequest {
  return UpdateCartItemQuantityRequestFromJSONTyped(json, false);
}

export function UpdateCartItemQuantityRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCartItemQuantityRequest {
  if (json == null) {
    return json;
  }
  return {

    'quantity': json['quantity'],
  };
}

export function UpdateCartItemQuantityRequestToJSON(json: any): UpdateCartItemQuantityRequest {
  return UpdateCartItemQuantityRequestToJSONTyped(json, false);
}

export function UpdateCartItemQuantityRequestToJSONTyped(value?: UpdateCartItemQuantityRequest | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'quantity': value['quantity'],
  };
}

