/* tslint:disable */
/* eslint-disable */
/**
 * Demo Shop API
 * A comprehensive API for managing an online store, providing endpoints for product catalog, user management, shopping cart operations, and order processing
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateUserAddressRequest
 */
export interface UpdateUserAddressRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateUserAddressRequest
   */
  street: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserAddressRequest
   */
  apartment: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserAddressRequest
   */
  city: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserAddressRequest
   */
  zip: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserAddressRequest
   */
  country: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserAddressRequest
   */
  region?: string | null;
}

/**
 * Check if a given object implements the UpdateUserAddressRequest interface.
 */
export function instanceOfUpdateUserAddressRequest(value: object): value is UpdateUserAddressRequest {
  if (!('street' in value) || value['street'] === undefined) return false;
  if (!('apartment' in value) || value['apartment'] === undefined) return false;
  if (!('city' in value) || value['city'] === undefined) return false;
  if (!('zip' in value) || value['zip'] === undefined) return false;
  if (!('country' in value) || value['country'] === undefined) return false;
  return true;
}

export function UpdateUserAddressRequestFromJSON(json: any): UpdateUserAddressRequest {
  return UpdateUserAddressRequestFromJSONTyped(json, false);
}

export function UpdateUserAddressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserAddressRequest {
  if (json == null) {
    return json;
  }
  return {

    'street': json['street'],
    'apartment': json['apartment'],
    'city': json['city'],
    'zip': json['zip'],
    'country': json['country'],
    'region': json['region'] == null ? undefined : json['region'],
  };
}

export function UpdateUserAddressRequestToJSON(json: any): UpdateUserAddressRequest {
  return UpdateUserAddressRequestToJSONTyped(json, false);
}

export function UpdateUserAddressRequestToJSONTyped(value?: UpdateUserAddressRequest | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'street': value['street'],
    'apartment': value['apartment'],
    'city': value['city'],
    'zip': value['zip'],
    'country': value['country'],
    'region': value['region'],
  };
}

