# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2
    labels:
      - 'dependencies'
    commit-message:
      prefix: 'fix'
      prefix-development: 'chore'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: '@types/react'
      - dependency-name: '@types/react-dom'
      - dependency-name: '@nrwl/*'
      - dependency-name: 'nx'
      - dependency-name: '@nx/*'
      - dependency-name: 'typescript'
      - dependency-name: '@types/node'
    groups:
      dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - 'react'
          - 'react-dom'
          - '@nrwl/*'
        update-types:
          - 'minor'
          - 'patch'
