/* tslint:disable */
/* eslint-disable */
/**
 * Demo Shop API
 * A comprehensive API for managing an online store, providing endpoints for product catalog, user management, shopping cart operations, and order processing
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UpdateUserPhoneRequest
 */
export interface UpdateUserPhoneRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateUserPhoneRequest
   */
  phone: string | null;
}

/**
 * Check if a given object implements the UpdateUserPhoneRequest interface.
 */
export function instanceOfUpdateUserPhoneRequest(value: object): value is UpdateUserPhoneRequest {
  if (!('phone' in value) || value['phone'] === undefined) return false;
  return true;
}

export function UpdateUserPhoneRequestFromJSON(json: any): UpdateUserPhoneRequest {
  return UpdateUserPhoneRequestFromJSONTyped(json, false);
}

export function UpdateUserPhoneRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserPhoneRequest {
  if (json == null) {
    return json;
  }
  return {
    phone: json['phone'],
  };
}

export function UpdateUserPhoneRequestToJSON(json: any): UpdateUserPhoneRequest {
  return UpdateUserPhoneRequestToJSONTyped(json, false);
}

export function UpdateUserPhoneRequestToJSONTyped(
  value?: UpdateUserPhoneRequest | null,
  ignoreDiscriminator: boolean = false
): any {
  if (value == null) {
    return value;
  }

  return {
    phone: value['phone'],
  };
}
