/* tslint:disable */
/* eslint-disable */
/**
 * Demo Shop API
 * A comprehensive API for managing an online store, providing endpoints for product catalog, user management, shopping cart operations, and order processing
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ProductListResponse, ProductResponse } from '../models';
import {
  ProductListResponseFromJSON,
  ProductListResponseToJSON,
  ProductResponseFromJSON,
  ProductResponseToJSON,
} from '../models';

export interface GetProductByIdRequest {
  id: number;
}

/**
 *
 */
export class ProductApi extends runtime.BaseAPI {
  /**
   * Get all products
   * Get all products
   */
  async getAllProductsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ProductListResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/v1/products`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, jsonValue => ProductListResponseFromJSON(jsonValue));
  }

  /**
   * Get all products
   * Get all products
   */
  async getAllProducts(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductListResponse> {
    const response = await this.getAllProductsRaw(initOverrides);
    return await response.value();
  }

  /**
   * Get product by id
   * Get product by id
   */
  async getProductByIdRaw(
    requestParameters: GetProductByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ProductResponse>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getProductById().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/v1/products/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(requestParameters['id']))),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, jsonValue => ProductResponseFromJSON(jsonValue));
  }

  /**
   * Get product by id
   * Get product by id
   */
  async getProductById(
    requestParameters: GetProductByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ProductResponse> {
    const response = await this.getProductByIdRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
