name: Version

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
    inputs:
      dry_run:
        type: boolean
        description: 'Dry run'
        default: false

concurrency:
  group: version
  cancel-in-progress: false

jobs:
  version:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.CW_DEPLOY_BOT_ID }}
          private-key: ${{ secrets.CW_DEPLOY_BOT_KEY }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Configure Git
        run: |
          git config --global user.name 'CW Deploy Bot'
          git config --global user.email 'noreply@github.com'

      - name: Pull latest changes
        run: git pull origin main

      - name: Check if version needs update
        id: check-version
        run: |
          # Check if there are any changes since last version tag
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "none")
          if [ "$LATEST_TAG" != "none" ]; then
            CHANGES=$(git log $LATEST_TAG..HEAD --oneline -- . ':!CHANGELOG.md' ':!package.json' ':!package-lock.json')
            if [ -z "$CHANGES" ]; then
              echo "No changes detected since last version, skipping version bump"
              echo "skip=true" >> $GITHUB_OUTPUT
            else
              echo "Changes detected, proceeding with version bump"
              echo "skip=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "No previous tag found, proceeding with version bump"
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Create new version
        if: ${{ !inputs.dry_run }}
        run: |
          touch CHANGELOG.md
          npx standard-version --infile CHANGELOG.md --commit-all
          git push --follow-tags origin main

      - name: Dry run
        if: ${{ inputs.dry_run }}
        run: npx standard-version --dry-run
